include:
  - .well-known

collections:
  pages:
    output: true
    permalink: /:path
  secret:
    output: true

defaults:
  - scope:
      path: "_secret/"
    values:
      layout: secret
      sitemap: false
  - scope:
      path: "_posts/"
    values:
      layout: post

url: "https://meow-d.github.io"

plugins:
  - jekyll-sitemap
