include:
  - .well-known

collections:
  pages:
    output: true
    permalink: /:path

defaults:
  - scope:
      path: "_posts/"
    values:
      layout: post

url: "https://meow-d.github.io"

plugins:
  - jekyll-sitemap
